global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'nest_app'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
